// Fungsi untuk membuat lencana lisensi
const renderLicenseBadge = (license) => {
  if (license !== 'None') {
    return `[![License](https://img.shields.io/badge/License-${license}-yellow.svg)](https://opensource.org/licenses/${license.replace('_', '-')})`;
  }
  return '';
};

// Fungsi untuk membuat link lisensi
const renderLicenseLink = (license) => {
  if (license !== 'None') {
    return `\n* [License](#license)\n`;
  }
  return '';
};

// Fungsi untuk membuat bagian lisensi
const renderLicenseSection = (license) => {
  if (license !== 'None') {
    return `## License

This project is licensed under the ${license.replace('_', ' ')} License.`;
  }
  return '';
};

// Fungsi utama untuk menghasilkan markdown
export const generateMarkdown = (data) => {
  return `# ${data.projectTitle}

${renderLicenseBadge(data.license)}

## Description

${data.description}

${data.liveUrl ? `### Live Demo\n\n[View Deployed Application](${data.liveUrl})\n` : ''}

## Table of Contents

* [Features](#features)
* [Installation](#installation)
* [Usage](#usage)${renderLicenseLink(data.license)}
* [Contributing](#contributing)
* [Author](#author)

## Features

${data.features.map(feature => `- ${feature}`).join('\n')}

## Installation

To install necessary dependencies, run the following command:

\`\`\`bash
${data.installation}
\`\`\`

## Usage

To use this application, run the following command:

\`\`\`bash
${data.usage}
\`\`\`

${renderLicenseSection(data.license)}

## Contributing

${data.contributing ? 'Contributions are welcome! Please feel free to fork the repository and submit a pull request.' : 'Contributions are not being accepted at this time.'}

## Author

**${data.author}**

* GitHub: [@${data.githubUsername}](https://github.com/${data.githubUsername})

---

✨ *This README was generated by [Perfect README](https://github.com/RyumaTsukiro/perfect-readme-generator)*
`;
};
